"use client";

import Link from "next/link";

export default function AdminTicketsPage() {
  return (
    <div className="p-8">
      <h1 className="text-2xl font-bold mb-4">Tickets Management</h1>
      <p className="mb-4">Manage all tickets generated by users and suppliers regarding orders, refunds, and more. (Functionality coming soon.)</p>
      <table className="w-full bg-white rounded shadow mb-6">
        <thead>
          <tr className="bg-gray-100">
            <th className="p-2 text-left">Ticket ID</th>
            <th className="p-2 text-left">Subject</th>
            <th className="p-2 text-left">Type</th>
            <th className="p-2 text-left">Status</th>
            <th className="p-2 text-left">Created By</th>
            <th className="p-2 text-left">Created At</th>
            <th className="p-2 text-right">Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td className="p-2">#TCK-001</td>
            <td className="p-2">Order not received</td>
            <td className="p-2">Order</td>
            <td className="p-2"><span className="px-2 py-1 rounded text-xs font-semibold bg-yellow-100 text-yellow-700">Open</span></td>
            <td className="p-2">john@example.com</td>
            <td className="p-2">2024-06-01</td>
            <td className="p-2 text-right space-x-2">
              <button className="text-blue-600 hover:text-blue-800">View</button>
              <button className="text-green-600 hover:text-green-800">Resolve</button>
            </td>
          </tr>
          <tr>
            <td className="p-2">#TCK-002</td>
            <td className="p-2">Refund request</td>
            <td className="p-2">Refund</td>
            <td className="p-2"><span className="px-2 py-1 rounded text-xs font-semibold bg-green-100 text-green-700">Closed</span></td>
            <td className="p-2">supplier@vendor.com</td>
            <td className="p-2">2024-06-02</td>
            <td className="p-2 text-right space-x-2">
              <button className="text-blue-600 hover:text-blue-800">View</button>
            </td>
          </tr>
        </tbody>
      </table>
      <Link href="/dashboard/admin">
        <button className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors">Back to Admin Dashboard</button>
      </Link>
    </div>
  );
} 